package blogPost;

import javax.persistence.*;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;
@Entity
public class BlogPost
{
    private String userName;

    private String subject;

    private String body;

    private String timeStamp;

    private long ID;

    @Id // @id indicates that this is a unique primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //@GeneratedValue indicates that value is automatically generated by the server
    @Column(name = "blogID")
    public long getID(){ return this.ID;}
    public void setID(long ID){this.ID = ID;}


    @Basic
    public String getTimeStamp() {return timeStamp;}
    public void setTimeStamp(String timeStamp) { this.timeStamp = timeStamp;}

    @Basic
    public String getUserName()
    {
        return userName;
    }
    public void setUserName(String customerName)
    {
        this.userName = customerName;
    }

    @Basic
    public String getSubject()
    {
        return subject;
    }
    public void setSubject(String subject)
    {
        this.subject = subject;
    }

    @Basic
    public String getBody()
    {
        return body;
    }
    public void setBody(String body)
    {
        this.body = body;
    }


}
